server:
  servlet:
    contextPath: /game
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gamedb
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
app:
  jwtSecret: superSecretOIASD(*@&#@)( #TODO change
  jwtExpirationInMs: 86400000
