server:
  servlet:
    contextPath: /game
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gamedb
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
